# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9MdeqLfnwNJ3qBgdrNKJqCQCClcZquF
"""

!pip install ultralytics
from ultralytics import YOLO
import random
import matplotlib.pyplot as plt
import cv2
from google.colab import files
import os

model = YOLO('yolov8n.pt')

def detect_and_show(image_path):
    results = model(image_path)
    res_img = results[0].plot()
    plt.imshow(cv2.cvtColor(res_img, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.show()
    names = model.names
    detected_classes = [names[int(box.cls)] for box in results[0].boxes]
    return detected_classes

score = 0
rounds = 3
target_classes = list(model.names.values())

for r in range(rounds):
    target = random.choice(target_classes)
    print(f"第 {r+1} 轮: 请上传一张包含 **{target}** 的图片！")

    uploaded = files.upload()
    img_path = list(uploaded.keys())[0]

    detected = detect_and_show(img_path)
    print("检测结果：", detected)

    if target in detected:
        score += 1
        print("✅ 正确！得分+1")
    else:
        print("❌ 没找到目标")

    os.remove(img_path)

print(f"🎉 游戏结束，总得分: {score}/{rounds}")